config/routes.rb
RssWatching::Application.routes.draw do

  devise_for :users

  root 'feeds#index'

  resources :items, :users

  resources :feeds do
    resources :items
  end
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_and_belongs_to_many :items

  validates_presence_of :name, :slug

  validates_uniqueness_of :name

  extend FriendlyId
  friendly_id :name, use: :slugged

end

app/models/item.rb
class Item < ActiveRecord::Base

  has_and_belongs_to_many :feeds

  belongs_to :user

  validates_presence_of :title, :article_link, :description, :date, :user_id

  validates_uniqueness_of :article_link

  validate :valid_article_link

  require 'net/http'
  def valid_article_link
    begin
      url = URI.parse(article_link)
      req = Net::HTTP.get_response(url.host, '/')
      logger.error "[valid_article_link] Dead link: #{req.code}"
      errors.add(:article_link, :dead) unless req.code == '200'
    rescue URI::InvalidURIError => e
      errors.add(:article_link, :invalid)
      logger.error "[valid_article_link] Error testing url: #{e}"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  #devise :ldap_authenticatable, :rememberable, :trackable
  devise :database_authenticatable, :rememberable, :trackable
  default_scope { order('last_name') }
  has_many :items
  #before_save :get_ldap_infos

  def get_ldap_infos
    self.email = Devise::LDAP::Adapter.get_ldap_param(self.email, "userPrincipalName").first
    self.last_name = Devise::LDAP::Adapter.get_ldap_param(self.email, "sn").first
    self.first_name = Devise::LDAP::Adapter.get_ldap_param(self.email, "givenname").first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #rescue_from DeviseLdapAuthenticatable::LdapException do |exception|
  #  render :text => exception, :status => 500
  #end
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

  def current_user
    UserDecorator.decorate(super) unless super.nil?
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user!, only: [:show]

  def index
    @feeds = Kaminari.paginate_array(FeedDecorator.decorate_collection(Feed.all)).page(params[:page])
  end

  def show
    respond_to do |format|
      format.html {}
      format.atom { render layout: false }
    end
  end

  def new
    @feed = Feed.new
  end

  def edit
  end

  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to feeds_path, notice: t('feed.create', name: @feed.name) }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to feeds_path, notice: t('feed.update', name: @feed.name) }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
  name = @feed.name
    @feed.destroy
      respond_to do |format|
      format.html { redirect_to feeds_url, notice: t('feed.destroyed', name: name) }
    end
  end

  private
  def set_feed
    @feed = Feed.friendly.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:name, item_ids: [])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :fix_datetime_params, only: [:create, :update]

  def index
    @items = Kaminari.paginate_array(ItemDecorator.decorate_collection(Item.all)).page(params[:page])
  end

  def show
    @item = @item.decorate
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_path, notice: t('item.create', name: @item.title) }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to items_path, notice: t('item.update', name: @item.title) }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
  name = @item.title
    @item.destroy
      respond_to do |format|
      format.html { redirect_to items_url, notice: t('item.destroyed', name: name) }
    end
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :article_link, :description, :date, :user_id, feed_ids: [])
  end

  def fix_datetime_params
      unless params[:item]["date"].empty? or params[:item]["time"].empty?
        date = Date.parse(params[:item]["date"])
        time = Time.parse(params[:item]["time"])
        datetime = DateTime.new(date.year, date.month, date.day, time.hour, time.min) 
        params[:item].merge!({"date" => datetime})
      end 
      params[:item].reject! {|k| k == 'time'}
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper

  def users
    User.all.collect {|u| [u.decorate.name, u.id]}
  end

  def feeds
    Feed.all.collect {|f| [f.name.capitalize, f.id]}
  end

end

app/views/feeds/_form.html.haml
= simple_form_for @feed, :html => {:class => 'form-horizontal'} do |f|

  .well
    = f.input :name

  .form_actions
    = f.button :submit, :class => 'btn btn-default'
    = link_to t('helpers.submit.cancel'), :back, :class => 'btn btn-default'

app/views/feeds/_listing.html.haml
- if feeds.empty?
  = t('feed.empty')

- else
  .row.paginate
    .col-md-8
      = paginate feeds
    .col-md-4
      %p.pull-right= [feeds.total_count.to_s, t('model.feeds').downcase].join(" ")

  %table.table.table-striped
    %thead
      %tr
        %th= t('feed.name')
        %th= t('feed.items_count')
        %th
    %tbody
      - feeds.each do |feed|
        %tr
          %td= feed.name
          %td= feed.items.count
          %td
            = link_to feed_path(feed, format: 'atom'), class: 'btn btn-default btn-sm', target: :blank, title: t('feed.show') do
              %span.fa.fa-rss
            = link_to edit_feed_path(feed), :class => 'btn btn-default btn-sm', :title => t('feed.edit') do
              %span.fa.fa-edit
            = link_to feed_path(feed), :class => 'btn btn-default btn-sm', :title => t('feed.destroy'), method: :delete, data: { confirm: t('feed.confirm_destroy') } do
              %span.fa.fa-times

app/views/feeds/edit.html.haml
%legend
  %h2= @feed.name

= render :partial => 'form'

app/views/feeds/index.html.haml
.row.bar
  .col-md-8
    .title.pull-left= t('model.feeds')
  .col-md-4
    .btn-group.pull-right
      = link_to new_feed_path, :class => 'btn btn-default', :title => t('feed.new') do
        %span.fa.fa-plus

#feeds.partial
  = render :partial => 'listing', :locals => {:feeds => @feeds}

app/views/feeds/new.html.haml
%legend
  %h2= t('feed.new')

= render :partial => 'form'

app/views/items/_form.html.haml
= simple_form_for @item, :html => {:class => 'form-horizontal'} do |f|

  .well
    = f.input :description
    = f.input :title
    = f.input :article_link
    = f.input :user_id, collection: users, selected: (@item.user.nil? ? current_user.id : @item.user.id)
    = f.input :date, as: :datetimepicker
    = f.association :feeds, collection: feeds, input_html: {multiple: 'multiple'}

  .form_actions
    = f.button :submit, :class => 'btn btn-default'
    = link_to t('helpers.submit.cancel'), :back, :class => 'btn btn-default'

app/views/items/_listing.html.haml
- if items.empty?
  = t('item.empty')

- else
  .row.paginate
    .col-md-8
      = paginate items
    .col-md-4
      %p.pull-right= [items.total_count.to_s, t('model.items').downcase].join(" ")

  %table.table.table-striped
    %thead
      %tr
        %th= t('item.title')
        %th= t('item.article_link')
        %th= t('item.date')
        %th= t('item.feeds')
        %th
    %tbody
      - items.each do |item|
        %tr
          %td= item.title
          %td= item.article_link
          %td= item.date
          %td= item.feeds_links
          %td
            = link_to item, class: 'btn btn-default btn-sm', title: t('item.show') do
              %span.fa.fa-eye
            = link_to edit_item_path(item), :class => 'btn btn-default btn-sm', :title => t('item.edit') do
              %span.fa.fa-edit
            = link_to item_path(item), :class => 'btn btn-default btn-sm', :title => t('item.destroy'), method: :delete, data: { confirm: t('item.confirm_destroy') } do
              %span.fa.fa-times

app/views/items/edit.html.haml
%legend
  %h2= @item.title

= render :partial => 'form'

app/views/items/index.html.haml
.row.bar
  .col-md-8
    .title.pull-left= t('model.items')
  .col-md-4
    .btn-group.pull-right
      = link_to new_item_path, :class => 'btn btn-default', :title => t('item.new') do
        %span.fa.fa-plus

#items.partial
  = render :partial => 'listing', :locals => {:items => @items}

app/views/items/new.html.haml
%legend
  %h2= t('item.new')

= render :partial => 'form'

app/views/items/show.html.haml
%legend.row
  %h2.pull-left= @item.title
  .btn-group.pull-right
    = link_to edit_item_path(@item), class: 'btn btn-default', title: t('item.edit') do
      %span.fa.fa-edit
    = link_to item_path(@item), class: 'btn btn-default', title: t('item.destroy'), method: :delete, data: { confirm: t('item.confirm_destroy') } do
      %span.fa.fa-trash-o

.well
  %dl.dl-horizontal
    %dt= t('item.title')
    %dd= @item.title
    %dt= t('item.description')
    %dd= @item.description
    %dt= t('item.article_link')
    %dd= @item.article_link
    %dt= t('item.date')
    %dd= @item.date
    %dt= t('item.user_id')
    %dd= @item.user.decorate.name
    %dt= t('item.feeds')
    %dd= @item.feeds_links

= link_to t('helpers.submit.back'), :back, :class => 'btn btn-default'

app/views/layouts/application.html.haml
%html
  %head
    = stylesheet_link_tag "application"
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css"
    = yield :stylesheet

    = javascript_include_tag "application"
    = yield :javascript

    = csrf_meta_tags

    %title
      Veille RSS

  %body
    - if current_user
      = render :partial => 'shared/top_bar'
    .container.main
      .row
        - if current_user
          .col-md-12
            - flash.each do |name, msg|
              %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
                %a.close{"data-dismiss" => "alert"} &#215;
                = content_tag :div, msg.html_safe, :id => "flash_#{name}" if msg.is_a?(String)    
            = yield
        - else
          .col-md-12
            = yield

app/views/shared/_top_bar.html.haml
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      = link_to 'VEILLE RSS', feeds_path, class: 'navbar-brand'

    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-left
        %li= link_to t('model.feeds'), feeds_path
        %li= link_to t('model.items'), items_path
      %ul.nav.navbar-nav.navbar-right
        %li= link_to current_user.name, '#'
        %li.pull-right.destroy
          = link_to destroy_user_session_path, method: :delete, alt: t('devise.logout') do
            = image_tag "exclamation.png", alt: t('devise.logout').html_safe, title: t('devise.logout'), class: :destroy